setup pre-commits
Byndyusoft/vite-template pull request #1
Opened 2024-12-03 11:13 UTC by glebfomin28

2024-12-04 14:58 UTC, Oustinger commented on .husky/commit-msg
> +npx --no -- commitlint --edit
Тут пробел случаем не лишний - `-- commitlint`?

2024-12-04 14:58 UTC, Oustinger commented on src/App.css
> +body div {
Почему не #root?

2024-12-04 15:00 UTC, Oustinger commented
@glebfomin28 Вынеси сюда или отдельным ПР функционал редактирования сообщения коммита с подтягиванием номера карточки из ветки, это очень полезная фича (а может его сделать отдельным пакетом и подключать как плагин @commitlint/config-conventional? 🤔 Это было бы ещё лучше!)

2024-12-04 15:01 UTC, Oustinger commented on src/App.css
> +body div {
Лучше вернуть #root, я думаю

2024-12-04 16:16 UTC, glebfomin28 commented on src/App.css
> +body div {
Там stylelint почему-то ругался на селектор #root, поэтому заменил. Перепроверю ещё раз

2024-12-12 06:56 UTC, glebfomin28 commented on src/App.css
> +body div {
Проверил, проблема в пакете @byndyusoft/stylelint-config, там правило на запрет ID-селекторов

2024-12-12 06:59 UTC, glebfomin28 commented on src/App.css
> +body div {
Переделал немного верстку, добавил пару новых div c классами. Думаю, будет не критично.

2024-12-12 07:11 UTC, glebfomin28 commented on .husky/commit-msg
> +npx --no -- commitlint --edit
Исправил

2024-12-12 15:48 UTC, Oustinger approved these changes

2025-02-15 10:43 UTC, Oustinger approved these changes

2025-02-15 12:10 UTC, sadcitizen requested changes

2025-02-15 12:10 UTC, sadcitizen commented on vite.config.ts
> -/* eslint-disable */
В этом файле отступы в 2 пробела, а должны быть в 4

2025-02-15 12:38 UTC, sadcitizen approved these changes

2025-02-15 12:38 UTC, merged